### PR TITLE
Add function to show open fds for process

### PR DESCRIPTION
**Pull request by SmilingNavern**
Add Fd struct and function to show it

### CODE REVIEW

**Comment by SmilingNavern** [comment]
Actually i rewrite it right now for better error handling.

**Comment by SmilingNavern** [comment]
@borntyping hello, i've added better error handling. Could you please review my PR?:)

**Comment by borntyping** [comment]
Sorry about taking so long to get round to this! I've merged this, and published a new version of `psutil` ([1.1.0](https://crates.io/crates/psutil/1.1.0)). Thanks for contributing :smiley:

**Comment by SmilingNavern** [comment]
@borntyping yey! thank you:) i'm glad you merged this

**Pull request merged**
