### PR TITLE
Change project metadata

### PR DESCRIPTION
**Pull request by borntyping**
This adds @rkday and @cjbassi to the `authors` list (ordered alphabetically) and changes the `repository` to https://github.com/rust-psutil/rust-psutil, where I intend to move this project if we merge this.

(I'm not actively working on or using this project at the moment, so this should make sure the project has a viable future. Thanks for all the effort you two have made / are doing / may do! 😄)

### CODE REVIEW

**Comment by cjbassi** [comment]
:+1: LGTM. Thanks!

**Comment by cjbassi** [comment]
Actually, I don't think we need to bump the version. Esp since I just merge a bunch of breaking stuff :P

**Comment by cjbassi** [comment]
Maybe we could just go ahead and move the project over to the organization now, and add @rkday later once he  responds? I don't really see any issues with moving it to the organization now.

**Comment by borntyping** [comment]
I'll wait a couple more days for a response and then move it. (I also need to fix this so it can be merged without conflicts, and I'm not able to do that over the weekend.)

**Comment by cjbassi** [comment]
Fixed the conflicts for ya :) and sounds good.

**Comment by borntyping** [comment]
I've moved the project to https://github.com/rust-psutil/rust-psutil. @borntyping, @rkday and @cjbassi should all have access to the project on GitLab and Crates.io now :)

**Comment by cjbassi** [comment]
Awesome, thanks @borntyping!

**Comment by rkday** [comment]
Sorry for the slow response - thanks for this!

**Pull request merged**
