### PR TITLE
Remove pidfile and getpid functions

### PR DESCRIPTION
**Pull request by cjbassi**
Since this is a breaking change, I also removed the legacy `system` module
and documented both removals in the newly added changelog. And
cleaned up the tests.

These functions seem somewhat unecessary and out of scope of
the project and removing them cleans things up imo, since initially I was
confused about their purpose. Let me know if there's an issues with
removing them.

### CODE REVIEW

**Comment by borntyping** [comment]
I think `getpid` and `getppid` are worth keeping - I'm more than happy to see the pidfile functions go.

**Comment by cjbassi** [comment]
It turns out that `getpid` is already in the standard library as `std::process::id()`. And `getppid` is unix only, so that should be put behind a conditional compilation flag.

**Comment by borntyping** [comment]
Released in 1.7.0, thanks :)

**Comment by cjbassi** [comment]
Thanks! Minor thing but since we removed some public interfaces it should technically be a major semver version jump, although I plan for some more breaking changes in #54 anyway :) so we can probably wait until that pr.

**Pull request merged**
